# Generated by Django 4.2.4 on 2023-08-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiko", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="status",
            field=models.TextField(
                choices=[("GOING", "GOING"), ("NOT_GOING", "NOT_GOING")],
                default="GOING",
            ),
            preserve_default=False,
        ),
    ]
